Repository Orange-OpenSource/hurl, pull requests merged in 2022-08, with the labels that each got.

#716 Fix bin dir for update-crates.yml
  .github/workflows/update-crates.yml
Labels: ci

#717 Delete emulated arm tests from ci
  .github/workflows/test.yml
Labels: ci

#720 Update crates
  Cargo.lock
  packages/hurl/Cargo.toml
Labels: dependencies, bot

#728 Always wait for checks when /accept a PR
  .github/workflows/accept-pull-request.yml
Labels: ci

#731 Make verbose and very-verbose logs more colored.
  integration/tests_ok/color.err
  integration/tests_ok/verbose.err.pattern
  integration/tests_ok/very_verbose.err.pattern
  packages/hurl/src/http/client.rs
  packages/hurl/src/http/debug.rs
  packages/hurl/src/http/request_debug.rs
  packages/hurl/src/http/response_debug.rs
  packages/hurl/src/main.rs
  packages/hurl/src/runner/entry.rs
  packages/hurl/src/util/logger.rs
Labels: enhancement

#740 Update crates
  Cargo.lock
  packages/hurl/Cargo.toml
Labels: dependencies, bot

#749 Add coverage report and badge to ci
  .github/workflows/coverage.yml
  README.md
  bin/docs/build_readme.py
  bin/install_grcov.sh
  packages/hurl/README.md
Labels: ci

#755 Update crates
  Cargo.lock
  packages/hurl/Cargo.toml
Labels: dependencies, bot

#777 Update crates
  Cargo.lock
  packages/hurl/Cargo.toml
Labels: dependencies, bot

#778 Update crates
  Cargo.lock
  packages/hurl/Cargo.toml
Labels: dependencies, bot

#792 Update crates
  Cargo.lock
  packages/hurl/Cargo.toml
  packages/hurlfmt/Cargo.toml
Labels: dependencies, bot

#793 Update crates
  Cargo.lock
  packages/hurl/Cargo.toml
  packages/hurlfmt/Cargo.toml
Labels: dependencies, bot
